"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { api } from "@/lib/api";
import { Federation } from "@/lib/types";

export default function FederationManagement() {
  const [items, setItems] = useState<Federation[]>([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [name, setName] = useState(""); const [registration, setRegistration] = useState("");
  const load = () => { setLoading(true); api.listFederations().then(setItems).catch((e: unknown) => setError(e instanceof Error ? e.message : "Unable to load federations.")).finally(() => setLoading(false)); };
  useEffect(load, []);
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { await api.createFederation({ name, registration_number: registration || null, city: "Chennai", state: "Tamil Nadu" }); setName(""); setRegistration(""); load(); } catch (e: unknown) { setError(e instanceof Error ? e.message : "Unable to create federation."); } finally { setSaving(false); } }
  return <section className="space-y-5"><div className="rounded-3xl border bg-white p-6 shadow-sm"><p className="text-sm text-blue-600">BridgePoint / Organizations</p><h1 className="mt-1 text-3xl font-bold">Federation management</h1><p className="mt-2 text-slate-500">Manage the federation layer above your societies.</p></div>{error && <p className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</p>}<form onSubmit={submit} className="grid gap-3 rounded-2xl border bg-white p-5 shadow-sm md:grid-cols-[1fr_1fr_auto]"><input required value={name} onChange={(e) => setName(e.target.value)} placeholder="Federation name" className="rounded-xl border px-4 py-3" /><input value={registration} onChange={(e) => setRegistration(e.target.value)} placeholder="Registration number (optional)" className="rounded-xl border px-4 py-3" /><button disabled={saving} className="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white">{saving ? "Creating..." : "Create Federation"}</button></form><div className="grid gap-4 md:grid-cols-2">{loading ? <p className="text-slate-500">Loading federations...</p> : items.length === 0 ? <p className="rounded-2xl border bg-white p-6 text-slate-500">No federations created yet.</p> : items.map((item) => <article key={item.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h2 className="text-xl font-semibold">{item.name}</h2><p className="text-sm text-slate-500">{item.registration_number || "Registration number not added"}</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs text-emerald-700">{item.status}</span></div><div className="mt-4 grid grid-cols-2 gap-3 text-sm md:grid-cols-4"><span><b>{item.society_count}</b><small className="block text-slate-500">Societies</small></span><span><b>{item.member_count}</b><small className="block text-slate-500">Total members</small></span><span><b>{item.active_member_count}</b><small className="block text-slate-500">Active</small></span><span><b>{item.pending_member_count}</b><small className="block text-slate-500">Pending</small></span></div><p className="mt-3 text-sm text-slate-500">Verified members: {item.verified_member_count}</p><Link href={`/admin/societies?federation_id=${item.id}`} className="mt-4 inline-block text-sm font-semibold text-blue-600">View societies →</Link></article>)}</div></section>;
}
