"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { api } from "@/lib/api";
import { Federation, Society } from "@/lib/types";

export default function SocietyManagement() {
  const [societies, setSocieties] = useState<Society[]>([]); const [federations, setFederations] = useState<Federation[]>([]); const [federationId, setFederationId] = useState(""); const [name, setName] = useState(""); const [search, setSearch] = useState(""); const [statusFilter, setStatusFilter] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const load = useCallback(() => { setLoading(true); api.listSocieties({ search: search || undefined, status: statusFilter || undefined }).then(setSocieties).catch((e: unknown) => setError(e instanceof Error ? e.message : "Unable to load societies.")).finally(() => setLoading(false)); }, [search, statusFilter]);
  useEffect(() => { api.listFederations().then(setFederations).catch(() => undefined); load(); }, [load]);
  async function submit(event: FormEvent) { event.preventDefault(); if (!federationId) return setError("Select a federation first."); setSaving(true); setError(""); try { await api.createSociety(Number(federationId), { name, city: "Chennai", state: "Tamil Nadu" }); setName(""); load(); } catch (e: unknown) { setError(e instanceof Error ? e.message : "Unable to create society."); } finally { setSaving(false); } }
  return <section className="space-y-5"><div className="rounded-3xl border bg-white p-6 shadow-sm"><p className="text-sm text-blue-600">BridgePoint / Organizations</p><h1 className="mt-1 text-3xl font-bold">Societies</h1><p className="mt-2 text-slate-500">Create and manage societies under your federation.</p></div>{error && <p className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</p>}<form onSubmit={submit} className="grid gap-3 rounded-2xl border bg-white p-5 shadow-sm md:grid-cols-[1fr_1fr_auto]"><select required value={federationId} onChange={(e) => setFederationId(e.target.value)} className="rounded-xl border px-4 py-3"><option value="">Select federation</option>{federations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input required value={name} onChange={(e) => setName(e.target.value)} placeholder="Society name" className="rounded-xl border px-4 py-3" /><button disabled={saving} className="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white">{saving ? "Creating..." : "Create Society"}</button></form><div className="flex flex-col gap-3 sm:flex-row"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search societies" className="w-full rounded-xl border bg-white px-4 py-3" /><select value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)} className="rounded-xl border bg-white px-4 py-3"><option value="">All statuses</option><option value="active">Active</option><option value="pending">Pending</option><option value="inactive">Inactive</option></select></div>{loading ? <p className="text-slate-500">Loading societies...</p> : societies.length === 0 ? <p className="rounded-2xl border bg-white p-6 text-slate-500">No societies found.</p> : <div className="grid gap-4 md:grid-cols-2">{societies.map((item) => <article key={item.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex justify-between gap-3"><div><h2 className="font-semibold">{item.name}</h2><p className="text-sm text-slate-500">{item.federation_name || "Federation unavailable"}</p></div><span className="text-xs text-emerald-700">{item.status}</span></div><div className="mt-4 flex gap-5 text-sm"><span><b>{item.member_count}</b> members</span><span><b>{item.verified_member_count}</b> verified</span></div><Link href={`/admin/societies/${item.id}`} className="mt-4 inline-block text-sm font-semibold text-blue-600">Open society →</Link></article>)}</div>}</section>;
}
