"use client";

import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import { CooperativeMembership, Society } from "@/lib/types";

export default function SocietyDetails({ id }: { id: number }) {
  const [society, setSociety] = useState<Society | null>(null); const [members, setMembers] = useState<CooperativeMembership[]>([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [workerId, setWorkerId] = useState("");
  const load = () => { setLoading(true); Promise.all([api.getSociety(id), api.listSocietyMembers(id)]).then(([s, m]) => { setSociety(s); setMembers(m); }).catch((e: unknown) => setError(e instanceof Error ? e.message : "Unable to load society.")).finally(() => setLoading(false)); };
  useEffect(() => { Promise.all([api.getSociety(id), api.listSocietyMembers(id)]).then(([s, m]) => { setSociety(s); setMembers(m); }).catch((e: unknown) => setError(e instanceof Error ? e.message : "Unable to load society.")).finally(() => setLoading(false)); }, [id]);
  async function addMember() { setError(""); try { await api.addSocietyMember(id, { user_id: Number(workerId) }); setWorkerId(""); load(); } catch (e: unknown) { setError(e instanceof Error ? e.message : "Unable to add worker."); } }
  async function changeMembership(memberId: number, action: "verify" | "suspend") { try { await (action === "verify" ? api.verifyMembership(memberId) : api.suspendMembership(memberId)); load(); } catch (e: unknown) { setError(e instanceof Error ? e.message : "Unable to update membership."); } }
  if (loading) return <p className="text-slate-500">Loading society...</p>;
  if (!society) return <p className="rounded-xl bg-red-50 p-4 text-red-700">{error || "Society not found."}</p>;
  return <section className="space-y-5"><div className="rounded-3xl border bg-white p-6 shadow-sm"><p className="text-sm text-blue-600">{society.federation_name || "Federation"}</p><h1 className="mt-1 text-3xl font-bold">{society.name}</h1><p className="mt-2 text-slate-500">{society.city || "Location not set"} · {society.status}</p></div>{error && <p className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</p>}<div className="grid gap-3 sm:grid-cols-4">{[["Overview", `${members.length} members`], ["Members", `${members.filter((m) => m.status === "active").length} active`], ["Jobs", "Society job linkage is not configured yet"], ["Skills", `${new Set(members.flatMap((m) => m.worker_name ? [m.worker_name] : [])).size} member records`]].map(([label, value]) => <div key={label} className="rounded-2xl border bg-white p-4 shadow-sm"><b>{label}</b><p className="mt-2 text-sm text-slate-500">{value}</p></div>)}</div><div className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-semibold">Add existing worker</h2><p className="mt-1 text-sm text-slate-500">Enter the authenticated worker&apos;s user ID. No duplicate memberships are allowed.</p><div className="mt-3 flex gap-3"><input value={workerId} onChange={(e) => setWorkerId(e.target.value)} placeholder="Worker user ID" type="number" className="rounded-xl border px-4 py-3" /><button onClick={addMember} disabled={!workerId} className="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white">Add member</button></div></div><div className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-semibold">Members</h2>{members.length === 0 ? <p className="mt-4 text-slate-500">No members yet.</p> : <div className="mt-4 space-y-3">{members.map((member) => <article key={member.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-slate-50 p-4"><div><b>{member.worker_name || "Worker"}</b><p className="text-sm text-slate-500">{member.membership_number} · {member.membership_type} · {member.status}</p></div><div className="flex gap-2">{member.status === "pending" && <button onClick={() => changeMembership(member.id, "verify")} className="rounded-lg border border-emerald-300 px-3 py-2 text-sm text-emerald-700">Verify</button>}{member.status === "active" && <button onClick={() => changeMembership(member.id, "suspend")} className="rounded-lg border border-red-300 px-3 py-2 text-sm text-red-700">Suspend</button>}</div></article>)}</div>}</div></section>;
}
